#!/usr/bin/env python3.10

import os
from PyPDF2 import PdfReader
from gtts import gTTS


home_directory = os.path.expanduser("~")


def pdf_to_text(pdf_path, start_page=None, end_page=None):
    reader = PdfReader(pdf_path)
    num_pages = len(reader.pages)
    start_page = start_page or 1
    end_page = end_page or num_pages

    text = ""
    for i in range(start_page-1, end_page):
        text += reader.pages[i].extract_text() + "\n"
    return text

def text_to_speech(text, output_file, lang='bn', slow=False):
    tts = gTTS(text=text, lang=lang, slow=slow)
    tts.save(output_file)
    print(f"[✓] Saved audio to {output_file}")

def main():
    pdf_path = input("Enter PDF path: ").strip()
    start_page = input("Start page (default 1): ").strip()
    end_page = input("End page (default last): ").strip()

    start_page = int(start_page) if start_page else None
    end_page = int(end_page) if end_page else None

    text = pdf_to_text(pdf_path, start_page, end_page)

    if not text.strip():
        print("[✗] No text found in this page range. Maybe scanned PDF.")
        return

    output_dir = f"{home_directory}/Music/Audiobook"
    os.makedirs(output_dir, exist_ok=True)
    filename = os.path.splitext(os.path.basename(pdf_path))[0]
    output_file = os.path.join(output_dir, f"{filename}_{start_page}_{end_page}.mp3")

    text_to_speech(text, output_file)


if __name__ == "__main__":
    main()
