#!/usr/bin/env python3.10

import os
import hashlib
import shutil


def file_hash(path):
    """Extracts the SHA256 hash of the file"""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def get_files(folder):
    """Gives the path of all files in the folder."""
    files = []
    for root, _, filenames in os.walk(folder):
        for name in filenames:
            files.append(os.path.join(root, name))
    return files


def clean_sub_folder(main_folder, sub_folder):
    print("📁 Reading MAIN folder (safe)...")
    main_hashes = set()

    for file in get_files(main_folder):
        try:
            main_hashes.add(file_hash(file))
        except:
            print(f"⚠️ Skipped (error): {file}")

    # duplicate folder create
    duplicate_folder = os.path.join(sub_folder, "duplicate")
    os.makedirs(duplicate_folder, exist_ok=True)

    print("🧹 Moving duplicates from SUB folder...")
    moved = 0

    for file in get_files(sub_folder):

        # I will skip the duplicate folder.
        if "duplicate" in file:
            continue

        try:
            if file_hash(file) in main_hashes:
                filename = os.path.basename(file)
                dest = os.path.join(duplicate_folder, filename)

                # If it has the same name, it will rename it.
                count = 1
                base, ext = os.path.splitext(filename)
                while os.path.exists(dest):
                    dest = os.path.join(duplicate_folder, f"{base}_{count}{ext}")
                    count += 1

                shutil.move(file, dest)
                moved += 1
                print(f"📦 Moved: {file} -> {dest}")

        except:
            print(f"⚠️ Error processing: {file}")

    print(f"\n✅ Done! Total files moved: {moved}")




if __name__ == "__main__":
    try:
        MAIN_FOLDER = input("Enter the main folder path : ")
        SUB_FOLDER  = input("Enter the sub folder path : ")
    except KeyboardInterrupt:
        print("\n❌ Program interrupted by user!")
        exit()

    clean_sub_folder(MAIN_FOLDER, SUB_FOLDER)
