#!/usr/bin/env python3.10

from pdf2image import convert_from_path
import os

# Enter the PDF file path
pdf_file = input("Enter Your PDF File Path: ")

# Get the folder containing the PDF file
path_folder = os.path.dirname(pdf_file)

# Output folder for PNG images
output_folder = os.path.join(path_folder, "pdf2png")
os.makedirs(output_folder, exist_ok=True)

# Convert PDF to PNG images
images = convert_from_path(pdf_file, dpi=300)  # You can adjust the dpi as needed
for i, image in enumerate(images):
    output_path = os.path.join(output_folder, f"{os.path.splitext(os.path.basename(pdf_file))[0]}_page{i+1}.png")
    image.save(output_path, "PNG")
    print(f"Saved: {output_path}")
