#!/usr/bin/env python3.10

import qrcode
from datetime import datetime
import os

data = input("Enter Data: ")

img = qrcode.make(data)

current_time = datetime.now().strftime("%Y%m%d_%H%M%S")

file_name = f"qrcode_{current_time}.png"

# Home directory path
home_dir = os.path.expanduser("~")

# Target folder path
folder_path = os.path.join(home_dir, "Pictures", "QrCode")

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Full file path
full_path = os.path.join(folder_path, file_name)

# Save image
img.save(full_path)

print("Saved as:", full_path)
