#!/usr/bin/env python3.10

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend
import base64
import os
import getpass


class SecureFile:

    def generate_key(self, password, salt):
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=100000,
            backend=default_backend()
        )
        return base64.urlsafe_b64encode(kdf.derive(password.encode()))

    def encrypt_file(self, input_file, password):
        salt = os.urandom(16)
        key = self.generate_key(password, salt)
        fernet = Fernet(key)

        with open(input_file, 'rb') as f:
            data = f.read()

        encrypted = fernet.encrypt(data)

        output_file = input_file + ".enc"

        with open(output_file, 'wb') as f:
            f.write(salt + encrypted)

        # 🔥 original file delete
        os.remove(input_file)

        print("✅ Encrypted & original deleted:", output_file)

    def decrypt_file(self, input_file, password):
        with open(input_file, 'rb') as f:
            data = f.read()

        salt = data[:16]
        encrypted_data = data[16:]

        key = self.generate_key(password, salt)
        fernet = Fernet(key)

        try:
            decrypted = fernet.decrypt(encrypted_data)
        except:
            print("❌ Wrong password or corrupted file!")
            return

        base = os.path.splitext(input_file)[0]

        with open(base, 'wb') as f:
            f.write(decrypted)

        # 🔥 encrypted file delete
        os.remove(input_file)

        print("✅ Decrypted & encrypted file deleted:", base)


if __name__ == "__main__":
    sf = SecureFile()

    print("1. Encrypt File")
    print("2. Decrypt File")

    choice = input("Enter choice (1/2): ")
    file_path = input("Enter file path: ")

    if choice == "1":
        password = getpass.getpass("Enter password: ")
        confirm = getpass.getpass("Confirm password: ")

        if password != confirm:
            print("❌ Passwords do not match!")
        else:
            sf.encrypt_file(file_path, password)

    elif choice == "2":
        password = getpass.getpass("Enter password: ")
        sf.decrypt_file(file_path, password)

    else:
        print("❌ Invalid choice")
        exit()